linusg/libjs-test262

README.md, main.py, requirements.txt
This adds the Runner class which executes the tests in parallel.
Number of workers defaults to the number of cores on the system but
can be changed with -c.
The Runner features a real-time progress bar to indicate its progress.
The Runner collects all the outcomes in a nested dict and reports them 
summed up for each directory in the tests tree. Directories with 0 tests
passed are not expanded.
=> Implement parallel test Runner with detailed reporting 

main.py
This eliminates all (16) cases of a test failing due to a runner exception :snake:
=> Strip invalid UTF-8 code points from test runner subprocess output

.clang-format, .gitignore, CMakeLists.txt, README.md, main.py, requirements.txt, setup.sh, src/$262Object.cpp, src/$262Object.h, src/AgentObject.cpp, src/AgentObject.h, src/GlobalObject.cpp, src/GlobalObject.h, src/main.cpp
Current results (+12!):
```
Old: 17724/40997 ( 43.23%) [ ✅ 17724 ❌ 22346 ⚠️ 35    📄 2     ⚙️ 125   💀 16    💥️ 749   ]
New: 17736/40997 ( 43.26%) [ ✅ 17736 ❌ 22334 ⚠️ 35    📄 2     ⚙️ 125   💀 16    💥️ 749   ]
✅ = SUCCESS, ❌ = FAILURE, ⚠️ = SKIPPED, 📄 = METADATA_ERROR, ⚙️ = HARNESS_ERROR, 💀 = TIMEOUT_ERROR, 💥️ = PROCESS_ERROR, 🐍 = RUNNER_EXCEPTION
```
cc @nooga @IdanHo
=> Replace (ab)use of js(1) with a custom LibJS test262 runner

setup.sh
The `[[` operator is a bash-only builtin.
=> Replace the bourne shell shebang with a bash one in setup.sh

README.md
The original link now 404's probably because of some reorganization in Serenity repo.
=> Fix LibJS link in README

src/$262Object.cpp, src/$262Object.h, src/GlobalObject.h
This fixes 29 test262 test cases (Those are not all of the test cases that were failing due to createRealm missing, since some of those tests actually test the Realm mechnaism itself, parts of which are not up to spec in LibJS)
=> Expose harness helpers

main.py, run_all_and_update_results.py
This allows us to drop the `python' prefix.
=> main: Make runner script executable

main.py, per_file_result_diff.py
This PR adds raw mode to `main.py`, which will output a .json file in the following format to stdout:
```
{
duration: 123.456,
results: {
"relative/path/to/test1": "PASSED",
"relative/path/to/test2": "FAILED",
"relative/path/to/test3": "SKIPPED",
...
}
```
This raw data dump makes it much easier to compare tests between runs and, most importantly, spot regressions. To compare two different files with the above format, I've added `raw_result_diff.py` (lmk if you can think of a better name). It will accept two files and print them in a [nice, easy to read way](https://i.imgur.com/SwL6KG8.png). Additionally, if the two files have different tests (if one was made with a newer clone of test262, for example), those differences will also be displayed. 
There is also a `--regression` flag, which …
=> Added per-file mode + a way to compare two different test results

run_all_and_update_results.py
Sowwy :(
I'm not sure what to do with the data that will be generated by the currently running PR though, should I patch that up?
=> Add the forgotten 'duration' entry to the bytecode results

run_all_and_update_results.py
Reverts linusg/libjs-test262#25
Looks like this affected performance negatively (+1.5 minutes), and barely increased core saturation, so just reverting it for now is probably the best.
I think that the real way to get more perf and increase saturation is reduce the amount of process creation and tear down. (Since we do that once for every test file right now)
=> Revert "Increase concurrency in CI if the MAX_RUNNER_THREADS env variable is available"

src/$262Object.cpp, src/AgentObject.cpp, src/GlobalObject.cpp
The old define_property helper method was removed.
If possible this should be merged just before the accompanying PR in Serenity is merged.
=> Use the new define_direct_property helper method

src/main.cpp
If possible this should be merged just before the accompanying PR in Serenity is merged.
=> Remove checks for the now defunct NativeProperty value type

CMakeLists.txt, cmake/FetchLagom.cmake, setup.sh
Move the CMake rules for the libjs-test262-runner binary into the source
directory so that the top level can be a super build that relies on
ExternalProject_Add for the Lagom dependency. This allows us to build
with a proper find_package(Lagom REQUIRED) build rule, which just feels
warm and fuzzy.
Based on @sin-ack 's previous PR #18
Requires https://github.com/SerenityOS/serenity/pull/9017
=> Build: Convert to super build that relies on Lagom shared libraries

run_all_and_update_results.py, setup.sh
While we have a build context handy that has libjs.so being built from
the user's provided serenity source directory, let's go ahead and build
test-js for the parser tests to use. Set the default path for test-js to
be the FetchContent'd build directory for Lagom as well.
=> Build: Build test-js along with the libjs-test262-runner by default

cmake/FetchLagom.cmake
We always want to BUILD_LAGOM. This regressed in serenity commit
https://github.com/SerenityOS/serenity/commit/904a268872416dc9b9f26c83fd0b1bd8b715c511
where BUILD_LAGOM began being set as a cache variable. The impact of
this on the libjs-test262 build is that after BUILD_LAGOM was set to OFF
in the cache, it would be overriden by the normal variable in FetchLagom
but not the first time it gets ran.
cc @alimpfard
=> CMake: Set BUILD_LAGOM as an internal cache variable

src/main.cpp
See https://github.com/SerenityOS/serenity/pull/10945
(Although they don't need to be merged at the same time.)
=> libjs-test262-runner: Rethrow exception on vm after bytecode run

src/main.cpp
Not destroying this timer results in every single test runner exit
causing an LSAN leak when running with AddressSanitizer enabled.
=> libjs-test262-runner: Destroy timeout POSIX timer on exit from main()

README.md, main.py, per_file_result_diff.py, run_all_and_update_results.py, src/main.cpp
To small fixes to the actual runner: 
- Fix test behavior with `raw` flag
- Detect TODO errors thrown within a promise or async function: `Diff Tests: -110 ❌   +110 📝`
Add a couple of options to main:
- `--forward-stderr` forward all the stderr output (cc @ADKaster does this seem useful or is outputting to a file better?)
- `--summary` only output the toplevel results i.e. `test 34983/45156 ( 77.47%) [ ✅ 34983 ❌ 2249  ⚙️ 112   💀 3     💥️ 199   📝 7610  ]` only
- `--per-file` now takes a argument of to which file to output the per-file results this will allow us to expose the current state of master on CI
Add a `-s / --silent` mode for comparing per-files with non the exact same tests. This is something I have been using for a long time by having a master.json file with the full results and …
=> Everything: Add a lot of convenient options

src/main.cpp
JS::Script and JS::SourceTextModule are now GC-allocated, so we can't
store them in NonnullRefPtr anymore.
=> Fix build after LibJS GC changes

README.md
Build/libjs-test262-runner no longer exists.
=> Update path to test262-runner in README

main.py
First, macOS no longer respects this resource limit anyways (I was not able to find a primary source, but see: https://crbug.com/853873).
More critically, our setrlimit invocation results in an exception raised with EINVAL on macOS. Even in C++, the following fails:
```c++
struct rlimit rl;
rl.rlim_cur = 512 * 1024 * 1024;
rl.rlim_max = RLIM_INFINITY;
int result = setrlimit(RLIMIT_AS, &rl);
// result == EINVAL
```
Resource limits seem to be non-functional on macOS in general; some even require recompiling Python from source to change the limits: https://bugs.python.org/issue40518
=> Do not set address space limit on macOS
